# Generated by Django 4.0.3 on 2022-04-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientsforrecipes',
            name='unique_recipe',
        ),
    ]
