# Generated by Django 4.0.3 on 2022-04-19 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsforrecipes',
            options={'verbose_name': 'Количество ингридиентов в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Связь тегов с рецептамиы'},
        ),
        migrations.AlterField(
            model_name='ingredientsforrecipes',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное кол-во ингрид-та - 1')], verbose_name='Количество ингридиента'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Уник. слаг'),
        ),
    ]
