# Generated by Django 4.0.3 on 2022-04-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourites',
            name='unique_favourites',
        ),
        migrations.RemoveConstraint(
            model_name='shopping_cart',
            name='unique_shopping_cart',
        ),
    ]
