# Generated by Django 4.0.3 on 2022-04-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow_follow_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
